// i_create_transaction_widget.hpp
#ifndef __UI__INCLUDE__UI__TRANSACTION__I_CREATE_TRANSACTION_WIDGET_HPP__
#define __UI__INCLUDE__UI__TRANSACTION__I_CREATE_TRANSACTION_WIDGET_HPP__

#include <qwidget.h>

#include "config/finance.hpp"

namespace ui
{

    /**
     * @brief Interface for widgets that create or edit a transaction
     *
     * All concrete transaction widgets implement this interface, allowing
     * the rest of the UI to hold and interact with them uniformly without
     * knowing about the specific transaction type or form layout.
     */
    class ICreateTransactionWidget : public QWidget
    {
        Q_OBJECT

       public:
        explicit ICreateTransactionWidget(QWidget* parent = nullptr);

        /**
         * @brief Get the transaction type of this widget, this will return the
         * type of transaction that this widget is designed to create (e.g.
         * Deposit, Withdrawal, Stock), allowing the owning dialog to determine
         * how to handle the transaction draft generated by this widget.
         *
         * @return TransactionType The transaction type of this widget
         */
        [[nodiscard]] virtual TransactionType getTransactionType() const = 0;

       signals:
        /**
         * @brief Emitted when the user confirms the form and a transaction
         * draft is ready to be submitted
         *
         * @param type The type of the transaction (e.g. Deposit, Withdrawal)
         */
        void createTransactionRequested(TransactionType type);
    };

}   // namespace ui

#endif   // __UI__INCLUDE__UI__TRANSACTION__I_CREATE_TRANSACTION_WIDGET_HPP__