// deposit_withdrawal_widget.cpp
#include "ui/transaction/deposit_withdrawal_widget.hpp"

#include <qboxlayout.h>
#include <qformlayout.h>
#include <qlabel.h>
#include <qpushbutton.h>

#include <stdexcept>

#include "finance/currency.hpp"
#include "ui/transaction/account_combo.hpp"
#include "ui/transaction/amount_row.hpp"
#include "utils/qt_helpers.hpp"
#include "utils/timestamp.hpp"

using utils::makeQChild;

namespace ui
{

    /**
     * @brief Construct a new Deposit Withdrawal Widget:: Deposit Withdrawal
     * Widget object
     *
     * @param type The type of transaction (Deposit or Withdrawal)
     * @param accounts A list of account drafts to populate the account combo
     * box with
     * @param parent The parent widget for this widget
     */
    DepositWithdrawalWidget::DepositWithdrawalWidget(
        TransactionType                   type,
        std::vector<drafts::AccountDraft> accounts,
        QWidget*                          parent
    )
        : ICreateTransactionWidget(parent),
          _type(type),
          _layout(new QFormLayout(this)),
          _accountCombo(makeQChild<AccountCombo>(std::move(accounts), this)),
          _amountRow(makeQChild<AmountRow>(this)),
          _currencyLabel(makeQChild<QLabel>(this)),
          _addButton(makeQChild<QPushButton>("Add Transaction", this))
    {
        setLayout(_layout);

        _layout->addRow("Account:", _accountCombo);

        auto* amountRowLayout = makeQChild<QHBoxLayout>();
        amountRowLayout->addWidget(_amountRow);
        amountRowLayout->addWidget(_currencyLabel);
        _layout->addRow("Amount:", amountRowLayout);

        _addButton->setEnabled(false);
        auto* buttonLayout = makeQChild<QHBoxLayout>();
        buttonLayout->addWidget(_addButton);
        _layout->addRow(buttonLayout);

        connect(
            _accountCombo,
            &AccountCombo::accountSelected,
            this,
            &DepositWithdrawalWidget::_onAccountSelected
        );
        connect(
            _amountRow,
            &AmountRow::validityChanged,
            this,
            &DepositWithdrawalWidget::_updateAddButton
        );
        connect(
            _amountRow,
            &AmountRow::valueChanged,
            this,
            &DepositWithdrawalWidget::_updateAddButton
        );
        connect(
            _addButton,
            &QPushButton::clicked,
            this,
            &DepositWithdrawalWidget::_emitOk
        );
    }

    /**
     * @brief Get the transaction type of this widget, this will return the type
     * of transaction that this widget is designed to create (either Deposit or
     * Withdrawal), allowing the owning dialog to determine how to handle the
     * transaction draft generated by this widget.
     *
     * @return TransactionType The transaction type of this widget
     */
    TransactionType DepositWithdrawalWidget::getTransactionType() const
    {
        return _type;
    }

    /**
     * @brief Get the transaction draft based on the current input in the
     * widget, this will generate a CreateCashTransactionDraft based on the
     * selected account and entered amount, which can then be used by the owning
     * dialog to create a new cash transaction in the store when the user
     * submits the form.
     *
     * @note The amount in the generated draft will be negative for Withdrawal
     * transactions and positive for Deposit transactions, reflecting the
     * direction of the cash flow for each transaction type.
     * @return drafts::CreateCashTransactionDraft The transaction draft
     * generated from the current input in the widget, which can be used to
     * create a new cash transaction in the store.
     */
    drafts::CreateCashTransactionDraft DepositWithdrawalWidget::getDraft() const
    {
        const auto account = _accountCombo->selected();

        if (!account.has_value())
            throw std::runtime_error("No account selected");

        auto cash = finance::Cash(account->currency, _amountRow->getAmount());
        cash      = _type == TransactionType::Deposit ? cash : -cash;

        auto entry = drafts::TransactionEntryDraft{account->id, cash};
        entry.setNeedsExternal(true);

        return {Timestamp{}, {entry}, std::nullopt};
    }

    /**
     * @brief Handle the selection of an account in the account combo box, this
     * will update the amount row to have the correct number of decimal places
     * for the selected account's currency, and will also update the currency
     * label to show the symbol of the selected account's currency, providing
     * feedback to the user about the currency they are entering an amount for,
     * and ensuring that the amount is properly formatted for the selected
     * account.
     *
     * @param account The selected account draft from the combo box, this is
     * used to determine the currency and formatting for the amount row and
     * currency label.
     */
    void DepositWithdrawalWidget::_onAccountSelected(
        const drafts::AccountDraft& account
    )
    {
        using finance::getMicroUnit;
        using finance::getSymbol;

        _amountRow->setNDecimalPlaces(getMicroUnit(account.currency));
        _currencyLabel->setText(getSymbol(account.currency).c_str());
        _updateAddButton();
    }

    /**
     * @brief Update the enabled state of the add button based on the current
     * input in the widget, this will enable the add button only when a valid
     * account is selected and a valid, non-zero amount is entered, providing
     * feedback to the user about when they can submit the form to create a new
     * transaction, and preventing invalid transactions from being created.
     *
     * The add button will be enabled only when:
     * - An account is selected in the account combo box
     * - The amount entered in the amount row is valid (e.g. properly formatted)
     * - The amount entered in the amount row is not zero (since a zero amount
     *   would not make sense for a deposit or withdrawal transaction)
     */
    void DepositWithdrawalWidget::_updateAddButton()
    {
        const auto isValid = _accountCombo->selected().has_value() &&
                             _amountRow->isValid() &&
                             _amountRow->getAmount() != 0;

        _addButton->setEnabled(isValid);
    }

    /**
     * @brief Emit the signal to create a new transaction, this will be called
     * when the user clicks the add button, and will emit the
     * createTransactionRequested signal with the transaction type of this
     * widget, allowing the owning dialog to handle the creation of the new
     * transaction based on the current input in the widget.
     *
     * The owning dialog can then call getDraft() on this widget to retrieve the
     * transaction draft based on the current input, and use that draft to
     * create a new transaction in the store. This allows the widget to
     * communicate with the dialog and controller to facilitate the creation of
     * new transactions based on user input, while keeping the widget focused on
     * managing the input and validation for the transaction details.
     */
    void DepositWithdrawalWidget::_emitOk()
    {
        emit createTransactionRequested(_type);
    }

}   // namespace ui