// stock_widget.cpp
#include "ui/transaction/stock_widget.hpp"

#include <qboxlayout.h>
#include <qformlayout.h>
#include <qlabel.h>
#include <qpushbutton.h>

#include "config/constants.hpp"
#include "finance/currency.hpp"
#include "ui/transaction/account_combo.hpp"
#include "ui/transaction/amount_row.hpp"
#include "utils/qt_helpers.hpp"

using utils::makeQChild;

namespace ui
{

    /**
     * @brief Construct a new Stock Widget:: Stock Widget object
     *
     * @param type The type of transaction (e.g. Stock)
     * @param accounts A list of account drafts to populate the account combo
     * box
     * @param referenceAccounts A list of account drafts to populate the
     * reference account combo box, this will be filtered based on the selected
     * primary account to only include accounts with the same currency
     * @param parent The parent widget for this widget
     */
    StockWidget::StockWidget(
        TransactionType                          type,
        std::vector<drafts::AccountDraft>        accounts,
        const std::vector<drafts::AccountDraft>& referenceAccounts,
        QWidget*                                 parent
    )
        : ICreateTransactionWidget(parent),
          _type(type),
          _layout(new QFormLayout(this)),
          _accountCombo(makeQChild<AccountCombo>(std::move(accounts), this)),
          _referenceAccountCombo(
              makeQChild<AccountCombo>(referenceAccounts, this)
          ),
          _quantityRow(makeQChild<AmountRow>(this)),
          _priceRow(makeQChild<AmountRow>(this)),
          _currencyLabel(makeQChild<QLabel>(this)),
          _addButton(makeQChild<QPushButton>("Add Transaction", this)),
          _tickerField(
              makeQChild<TickerField>(std::vector<QString>{"GOOG"}, this)
          ),
          _referenceAccounts(referenceAccounts)
    {
        setLayout(_layout);

        _layout->addRow("Account:", _accountCombo);
        _layout->addRow("Reference Account:", _referenceAccountCombo);
        _layout->addRow("Ticker:", _tickerField);

        auto* quantityRowLayout = makeQChild<QHBoxLayout>();
        quantityRowLayout->addWidget(_quantityRow);
        _layout->addRow("Quantity:", quantityRowLayout);
        _quantityRow->setNDecimalPlaces(Constants::getMicroUnitsPrecision());

        auto* amountRowLayout = makeQChild<QHBoxLayout>();
        amountRowLayout->addWidget(_priceRow);
        amountRowLayout->addWidget(_currencyLabel);
        _layout->addRow("Stock Price:", amountRowLayout);

        _referenceAccountCombo->setEnabled(false);

        _addButton->setEnabled(false);
        auto* buttonLayout = makeQChild<QHBoxLayout>();
        buttonLayout->addWidget(_addButton);
        _layout->addRow(buttonLayout);

        connect(
            _accountCombo,
            &AccountCombo::accountSelected,
            this,
            &StockWidget::_onAccountSelected
        );
        connect(
            _referenceAccountCombo,
            &AccountCombo::accountSelected,
            this,
            &StockWidget::_onReferenceAccountSelected
        );
        connect(
            _priceRow,
            &AmountRow::validityChanged,
            this,
            &StockWidget::_updateAddButton
        );
        connect(
            _priceRow,
            &AmountRow::valueChanged,
            this,
            &StockWidget::_updateAddButton
        );
        connect(_addButton, &QPushButton::clicked, this, &StockWidget::_emitOk);
    }

    /**
     * @brief Get the transaction type of this widget, this will return the type
     * of transaction that this widget is designed to create (either Deposit or
     * Withdrawal), allowing the owning dialog to determine how to handle the
     * transaction draft generated by this widget.
     *
     * @return TransactionType The transaction type of this widget
     */
    TransactionType StockWidget::getTransactionType() const { return _type; }

    /**
     * @brief Handle the selection of a primary account, this will be called
     * when the user selects a primary account from the account combo box, and
     * should handle updating the UI to reflect the selected account (e.g.
     * updating the currency label to show the currency of the selected
     * account), as well as filtering the reference accounts to only include
     * accounts with the same currency as the selected primary account, ensuring
     * that the user can only select valid reference accounts for the stock
     * transaction.
     *
     * @param account The account draft of the selected primary account, this is
     * used to determine the currency of the selected account for updating the
     * UI and filtering the reference accounts.
     */
    void StockWidget::_onAccountSelected(const drafts::AccountDraft& account)
    {
        using finance::getMicroUnit;
        using finance::getSymbol;

        _priceRow->setNDecimalPlaces(getMicroUnit(account.currency));
        _currencyLabel->setText(getSymbol(account.currency).c_str());

        std::vector<drafts::AccountDraft> referenceAccounts;

        for (const auto& referenceAccount : _referenceAccounts)
        {
            if (referenceAccount.currency == account.currency)
                referenceAccounts.push_back(referenceAccount);
        }

        _referenceAccountCombo->resetSelection();
        _referenceAccountCombo->updateAccounts(std::move(referenceAccounts));
        _referenceAccountCombo->setEnabled(true);
        _updateAddButton();
    }

    /**
     * @brief Handle the selection of a reference account, this will be called
     * when the user selects a reference account from the reference account
     * combo box, and should handle updating the UI to reflect the selected
     * reference account (if necessary), as well as enabling the add button if
     * all required fields are valid and filled out, allowing the user to
     * proceed with creating the stock transaction once they have selected a
     * valid reference account.
     *
     * @param account The account draft of the selected reference account, this
     * is used to determine if a valid reference account has been selected for
     * enabling the add button.
     */
    void StockWidget::_onReferenceAccountSelected(
        const drafts::AccountDraft& /*account*/
    )
    {
        _updateAddButton();
    }

    /**
     * @brief Update the enabled state of the add button, this should check if
     * all required fields for creating a stock transaction are valid and filled
     * out (e.g. a primary account is selected, a reference account is selected,
     * the quantity and price are valid and non-zero), and then enable or
     * disable the add button accordingly, ensuring that the user can only
     * proceed with creating the stock transaction once all necessary
     * information has been provided and is valid.
     */
    void StockWidget::_updateAddButton()
    {
        const auto isValid =
            _accountCombo->selected().has_value() &&
            _referenceAccountCombo->selected().has_value() &&
            _priceRow->isValid() && _quantityRow->getAmount() != 0 &&
            _priceRow->getAmount() != 0 && _quantityRow->isValid();

        _addButton->setEnabled(isValid);
    }

    /**
     * @brief Emit the signal to create the transaction, this will be called
     * when the user clicks the add button, and should emit a signal with the
     * transaction draft generated from the information entered in this widget,
     * allowing the owning dialog to handle creating the transaction in the
     * store based on the provided draft. This allows the widget to communicate
     * with the rest of the UI and trigger the creation of a new stock
     * transaction once the user has entered all necessary information and is
     * ready to proceed.
     */
    void StockWidget::_emitOk() { emit createTransactionRequested(_type); }

}   // namespace ui